### ISSUE TITLE
Correct signature for AvroSerializer to_dict and AvroDeserializer from_dict

### ISSUE THREAD

**Issue by dbendall** [benbenbang/types-confluent-kafka#154]
### Initial Checks

- [X] I confirm that I'm using Types-Confluent-Kafka

### Description

Hi Ben, 
Just discovered this package and it's been a great help already so many thanks to you for publishing it.

I have noticed a small issue on the `AvroSerializer` `to_dict` and `AvroDesrializer` `from_dict` signatures in that they do not specify the expected return types causing the following mypy errors:

```
reproduce.py:13: error: Argument "from_dict" to "AvroDeserializer" has incompatible type "Callable[[dict[Any, Any], SerializationContext], object]"; expected "Optional[Callable[[dict[Any, Any]], SerializationContext]]"  [arg-type]
reproduce.py:19: error: Argument "to_dict" to "AvroSerializer" has incompatible type "Callable[[object, SerializationContext], dict[Any, Any]]"; expected "Optional[Callable[[object], SerializationContext]]"  [arg-type]
```

I believe the type signatures should be as follows:
```
to_dict: Callable[[object, SerializationContext], dict[Any, Any]] | None
```
```
from_dict: Callable[[dict[Any, Any], SerializationContext], object] | None
```

I'm happy to put together a PR if that is convenient for you.

### Example Code

```Python
from typing import Any

from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry import avro
from confluent_kafka.serialization import SerializationContext

registry: SchemaRegistryClient

def dict_to_object(obj: dict[Any, Any], ctx: SerializationContext) -> object:
    """Convert decoded dict to an object"""
    return object()

avro.AvroDeserializer(registry, from_dict=dict_to_object)

def object_to_dict(obj: object, ctx: SerializationContext) -> dict[Any, Any]:
    """Convert object to dict for serialization"""
    return dict()

avro.AvroSerializer(registry, schema_str="...", to_dict=object_to_dict)
```

### Python, verion of Types-confluent-kafka. verion of Confluent-kafka-python, your applications settings & OS Version

```Text
confluent-kafka==2.2.0
types-confluent-kafka==1.0.0

OS: Ubuntu 23.04 x86_64
Python: 3.9.18
```

### Affected Components

- [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`)
- [ ] Apache Kafka broker version
- [ ] Client configuration: `{...}` is provided
- [X] Operating system is provided
- [ ] Provide IDE screenshot if it's possible

**Comment by benbenbang** [comment]
hello @dbendall 

Thanks again. The fix has been released. please check [1.0.1 on pypi](https://pypi.org/project/types-confluent-kafka/1.0.1/)
