### ISSUE TITLE
More concrete type annotations

### ISSUE THREAD

**Issue by navoyan** [benbenbang/types-confluent-kafka#158]
### Preliminary Checks

- [X] I've searched Google & GitHub for similar requests and found none.
- [X] I've reviewed the [confluent intro page](https://docs.confluent.io/kafka-clients/python/current/overview.html) and [the confluent kafka python docs](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html) and believe this feature is missing from the typings.
- [X] I understand that this repository is specifically for type annotations of the Kafka client. If my request is about Kafka client features or functionalities, I need to raise it in the [Confluent Kafka Python repo](https://github.com/confluentinc/confluent-kafka-python).

### Feature Details

Add more specific type annotations to be used with tools like [pyright](https://github.com/microsoft/pyright) in strict mode.

Pyright in strict mode requires all generic types to be fully specified. Because of this, some method calls, although appearing to be valid, produce an error:
```py
def report_delivery(error: KafkaError | None, msg: Message) -> None:
    if error is not None:
        print(error)

producer.produce(topic, value, on_delivery=report_delivery)
# error: Type of "produce" is partially unknown
#    Type of "produce" is "(topic: str, value: str | bytes | None = None, key: str | bytes | None = None, partition: int | None = None, on_delivery: ((...) -> Unknown) | None = None, timestamp: int = 0, headers: dict[str, str | bytes] | list[tuple[str, str | bytes]] | None = None) -> None" (reportUnknownMemberType)
```

Please take a look at #159

**Comment by benbenbang** [comment]
Hello @navoyan, thanks for the feedback and PR!

I will take a look this weekend.
