### ISSUE TITLE
Typo in Producer.send_offsets_to_transaction()

### ISSUE THREAD

**Issue by mannerydhe** [benbenbang/types-confluent-kafka#193]
### Initial Checks

- [X] I confirm that I'm using Types-Confluent-Kafka

### Description

The Producer class has a function called `send_offsets_to_transactions()`. It should be `send_offsets_to_transaction()` (without the 's')
https://github.com/confluentinc/confluent-kafka-python/blob/a6d2e1e41a858cde930bf5c5d5951d2e90c573ad/src/confluent_kafka/src/Producer.c#L435

### Python, verion of Types-confluent-kafka. verion of Confluent-kafka-python, your applications settings & OS Version

```Text
confluent-kafka==2.4.0
types-confluent-kafka==1.2.1
```

### Affected Components

- [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`)
- [ ] Apache Kafka broker version
- [ ] Client configuration: `{...}` is provided
- [ ] Operating system is provided
- [ ] Provide IDE screenshot if it's possible

**Comment by benbenbang** [comment]
Fixed! Sorry for the late reply and thanks for the contribution 💪🏻  @mannerydhe 

I will do a release tomorrow morning (CET)
