### ISSUE TITLE
Topic/Partition related admin functions return Future[None]

### ISSUE THREAD

**Issue by ronchler** [benbenbang/types-confluent-kafka#201]
### Initial Checks

- [X] I confirm that I'm using Types-Confluent-Kafka

### Description

Thank you for the awesome work!

https://github.com/benbenbang/types-confluent-kafka/blob/c9f9e1843fc66fc09f18d77de1eb51c9fa0b15b4/confluent_kafka-stubs/admin/__init__.pyi#L63

https://github.com/confluentinc/confluent-kafka-python/blob/dc3114afd15d56a828bcfb48f1601c4c3f076d78/src/confluent_kafka/admin/__init__.py#L568-L569

https://github.com/benbenbang/types-confluent-kafka/blob/c9f9e1843fc66fc09f18d77de1eb51c9fa0b15b4/confluent_kafka-stubs/admin/__init__.pyi#L66

https://github.com/confluentinc/confluent-kafka-python/blob/dc3114afd15d56a828bcfb48f1601c4c3f076d78/src/confluent_kafka/admin/__init__.py#L600-L601

https://github.com/benbenbang/types-confluent-kafka/blob/c9f9e1843fc66fc09f18d77de1eb51c9fa0b15b4/confluent_kafka-stubs/admin/__init__.pyi#L75

https://github.com/confluentinc/confluent-kafka-python/blob/dc3114afd15d56a828bcfb48f1601c4c3f076d78/src/confluent_kafka/admin/__init__.py#L641-L642

Should return `Future[None]`

Also

https://github.com/benbenbang/types-confluent-kafka/blob/c9f9e1843fc66fc09f18d77de1eb51c9fa0b15b4/confluent_kafka-stubs/admin/__init__.pyi#L81

will just return None. Not sure how to annotate, that the future might throw a `KafkaException`

https://github.com/confluentinc/confluent-kafka-python/blob/dc3114afd15d56a828bcfb48f1601c4c3f076d78/src/confluent_kafka/admin/__init__.py#L719-L720

### Example Code

```Python
.
```

### Python, verion of Types-confluent-kafka. verion of Confluent-kafka-python, your applications settings & OS Version

```Text
.
```

### Affected Components

- [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`)
- [ ] Apache Kafka broker version
- [ ] Client configuration: `{...}` is provided
- [ ] Operating system is provided
- [ ] Provide IDE screenshot if it's possible

**Comment by benbenbang** [comment]
Hello @ronchler 

Thanks for the report. According to [PEP 484](https://peps.python.org/pep-0484/)., which is the guiding document for typing hints in Python, while it does not provide specific details on handling exceptions in the `Future`, it outlines how to use type hints and the typing module to annotate function signatures. You can read more about [PEP 484](https://peps.python.org/pep-0484/).

here's the summary of handling [Exceptions](https://peps.python.org/pep-0484/#exceptions):
> No syntax for listing explicitly raised exceptions is proposed. Currently, the only known use case for this feature is documentational, in which case the recommendation is to put this information in a docstring.
