### ISSUE TITLE
Missing annotations for confluent v2.5.0

### ISSUE THREAD

**Issue by mj0nez** [benbenbang/types-confluent-kafka#202]
### Preliminary Checks

- [X] I've searched Google & GitHub for similar requests and found none.
- [X] I've reviewed the [confluent intro page](https://docs.confluent.io/kafka-clients/python/current/overview.html) and [the confluent kafka python docs](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html) and believe this feature is missing from the typings.
- [X] I understand that this repository is specifically for type annotations of the Kafka client. If my request is about Kafka client features or functionalities, I need to raise it in the [Confluent Kafka Python repo](https://github.com/confluentinc/confluent-kafka-python).

### Feature Details

With the latest version of `confluent-kafka` the stubs are missing some annotations, mainly for the `AdminClient`. We should add them.

**Comment by benbenbang** [comment]
thanks for the contribution
